/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph2;

//import org.jgrapht.graph.SimpleWeightedGraph;
//import org.jgarpht.graph.DefaultWeightedEdge;
//import org.jgrapht.alg.shortestpath.DijkstraShortestPa(Graph).th;
import org.jgrapht.alg.shortestpath.DijkstraShortestPath;
import org.jgrapht.graph.SimpleWeightedGraph;
import org.jgrapht.graph.DefaultWeightedEdge;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        SimpleWeightedGraph<String, DefaultWeightedEdge> myGraph;
        myGraph = new SimpleWeightedGraph<>(DefaultWeightedEdge.class);

        String malenane = "malenane";
        String nelspruit = "nelspruit";
        String witbank = "witbank";
        String johannesburg = "johannesburg";
        String pretoria = "pretoria";
        String midrand = "midrand";
        String kemptopark = "kemptopark";
        String centurion = "centurion";
        String polokwane = "polokwane";
        String thohoyandou = "thohoyandou";

        myGraph.addVertex(malenane);
        myGraph.addVertex(nelspruit);
        myGraph.addVertex(witbank);
        myGraph.addVertex(johannesburg);
        myGraph.addVertex(midrand);
        myGraph.addVertex(kemptopark);
        myGraph.addVertex(centurion);
        myGraph.addVertex(polokwane);
        myGraph.addVertex(thohoyandou);
        myGraph.addVertex(pretoria);

        DefaultWeightedEdge maleNelEdge = myGraph.addEdge(malenane, nelspruit);
        myGraph.setEdgeWeight(maleNelEdge, 37);
        
      

        DefaultWeightedEdge nelsWit = myGraph.addEdge(nelspruit, witbank);
        myGraph.setEdgeWeight(nelsWit, 15);

        DefaultWeightedEdge nelsKempto = myGraph.addEdge(nelspruit, kemptopark);
        myGraph.setEdgeWeight(nelsKempto, 40);

        DefaultWeightedEdge kemptoMid = myGraph.addEdge(kemptopark, midrand);
        myGraph.setEdgeWeight(kemptoMid, 20);

        DefaultWeightedEdge midJohannes = myGraph.addEdge(midrand, johannesburg);
        myGraph.setEdgeWeight(midJohannes, 10);

        DefaultWeightedEdge midCent = myGraph.addEdge(midrand, centurion);
        myGraph.setEdgeWeight(midCent, 5);

        DefaultWeightedEdge centPre = myGraph.addEdge(centurion, pretoria);
        myGraph.setEdgeWeight(centPre, 30);

        DefaultWeightedEdge witjohnes = myGraph.addEdge(witbank, johannesburg);
        myGraph.setEdgeWeight(witjohnes, 60);

        DefaultWeightedEdge johannePre = myGraph.addEdge(johannesburg, pretoria);
        myGraph.setEdgeWeight(johannePre, 50);

        DefaultWeightedEdge prePolo = myGraph.addEdge(pretoria, polokwane);
        myGraph.setEdgeWeight(prePolo, 90);

        DefaultWeightedEdge poloThoho = myGraph.addEdge(polokwane, thohoyandou);
        myGraph.setEdgeWeight(poloThoho, 200);

        System.out.println("My Graph of all cities" + myGraph.toString());

        DijkstraShortestPath shortestPath = new DijkstraShortestPath(myGraph);

        System.out.println("The shortest path from malenane and thohoyanduou is : " + shortestPath.getPath(malenane, thohoyandou));

        System.out.println("The weight between malenane and thohoyanduou " + shortestPath.getPath(malenane, thohoyandou).getWeight());

    }
}
